framework:
  secret: '%env(APP_SECRET)%'
  form: ~
  csrf_protection: { enabled: true }
  default_locale: pl
  validation: { enable_annotations: true }
  session:
    storage_factory_id: session.storage.factory.native
    handler_id:  session.handler.native_file
    save_path: "%kernel.project_dir%/var/sessions/%kernel.environment%"
  assets:
    json_manifest_path: '%kernel.project_dir%/public_html/build/manifest.json'
  php_errors:
    log: true
