framework:
  secret: '%env(APP_SECRET)%'
  form: ~
  csrf_protection: { enabled: true }
  default_locale: pl
  validation: { enable_annotations: true }
  templating:
    engines: ['twig']
  session:
    # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
    handler_id:  session.handler.native_file
    save_path: "%kernel.project_dir%/var/sessions/%kernel.environment%"
  assets:
    json_manifest_path: '%kernel.project_dir%/public_html/build/manifest.json'
  php_errors:
    log: true
