twig:
    paths: ['%kernel.project_dir%/templates']
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        image_collection_url: "%image.collection.url%"
        image_collection_width: "%image.collection.width%"
        image_collection_height: "%image.collection.height%"
        image_collection_mobile_width: "%image.collection.mobile.width%"
        image_collection_mobile_height: "%image.collection.mobile.height%"

        image_product_url: "%image.product.url%"
        image_product_big_width: "%image.product.big.width%"
        image_product_big_height: "%image.product.big.height%"
        image_product_small_width: "%image.product.small.width%"
        image_product_small_height: "%image.product.small.height%"

        samples_count: 2

        menu: '@Decarte\Shop\Service\View\Menu\Menu'

        cart: '@Decarte\Shop\Repository\Order\SessionOrderRepository'
        samples: '@Decarte\Shop\Repository\Order\SessionSamplesOrderRepository'

        google_analytics: "%env(GOOGLE_ANALYTICS)%"
