language: php

php:
  - '7.1'
  - '7.2'

cache:
  directories:
    - $HOME/.composer/cache/files

install:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install -o

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs --standard=PSR2 src tests
