language: php

php:
  - '7.3'

cache:
  directories:
    - $HOME/.composer/cache/files

install:
  - composer install -o

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs --standard=PSR2 src tests
  - vendor/bin/phpstan analyse --level 5 src tests
