version: '3'

services:
  php:
    build: docker/php-fpm
    volumes:
      - .:/var/www
    depends_on:
      - mailcatcher
      - mysql

  nginx:
    build: docker/nginx
    ports:
      - "8080:80"
    depends_on:
      - php
    volumes:
      - .:/var/www

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=decarte
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_USER=decarte
      - MYSQL_PASSWORD=12345
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"

  node:
    image: node:10
    user: node
    environment:
      - NODE_ENV=production
    volumes:
      - .:/var/www
    working_dir: /var/www

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"

volumes:
  .:
