imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: pl

    image.collection.url: "zaproszenia/kolekcje"
    image.collection.directory: "%kernel.root_dir%/../public_html/%image.collection.url%"
    image.collection.width: 176
    image.collection.height: 117
    image.collection.quality: 85

    image.series.url: "zaproszenia/serie"
    image.series.directory: "%kernel.root_dir%/../public_html/%image.series.url%"
    image.series.width: 482
    image.series.height: 321
    image.series.quality: 90

    image.product.big.url: "zaproszenia/produkty/duze"
    image.product.big.directory: "%kernel.root_dir%/../public_html/%image.product.big.url%"
    image.product.big.width: 720
    image.product.big.height: 480
    image.product.big.quality: 90

    image.product.small.url: "zaproszenia/produkty/male"
    image.product.small.directory: "%kernel.root_dir%/../public_html/%image.product.small.url%"
    image.product.small.width: 230
    image.product.small.height: 153
    image.product.small.quality: 85

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        image_collection_url: "%image.collection.url%"
        image_collection_width: "%image.collection.width%"
        image_collection_height: "%image.collection.height%"

        image_series_url: "%image.series.url%"
        image_series_width: "%image.series.width%"
        image_series_height: "%image.series.height%"

        image_product_big_url: "%image.product.big.url%"
        image_product_big_width: "%image.product.big.width%"
        image_product_big_height: "%image.product.big.height%"

        image_product_small_url: "%image.product.small.url%"
        image_product_small_width: "%image.product.small.width%"
        image_product_small_height: "%image.product.small.height%"

        menu: "@menu"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Slugify Configuration
cocur_slugify:
    lowercase: true
    rulesets: [ "polish" ]

# Sentry error reporting
sentry:
    dsn: "%sentry_dsn%"
