imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: pl

    image.collection.url: "zaproszenia/kolekcje"
    image.collection.directory: "%kernel.root_dir%/../public_html/%image.collection.url%"
    image.collection.width: 408
    image.collection.height: 306
    image.collection.quality: 80

    image.product.url: "zaproszenia/produkty"
    image.product.directory: "%kernel.root_dir%/../public_html/%image.product.url%"

    image.product.big.width: 830
    image.product.big.height: 622
    image.product.big.quality: 80

    image.product.small.width: 267
    image.product.small.height: 200
    image.product.small.quality: 80

    samples_count: 2

    admin.mail: "%admin_mail%"

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets:
        json_manifest_path: '%kernel.project_dir%/public_html/build/manifest.json'
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        image_collection_url: "%image.collection.url%"
        image_collection_width: "%image.collection.width%"
        image_collection_height: "%image.collection.height%"

        image_product_url: "%image.product.url%"
        image_product_big_width: "%image.product.big.width%"
        image_product_big_height: "%image.product.big.height%"
        image_product_small_width: "%image.product.small.width%"
        image_product_small_height: "%image.product.small.height%"

        samples_count: "%samples_count%"

        menu: "@menu"

        cart: "@temporary_order_repository"

        google_analytics: "%google_analytics%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        options:
            1002: SET NAMES utf8

        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true

stof_doctrine_extensions:
    default_locale: pl_PL
    orm:
        default:
            softdeleteable: true
            timestampable: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    port:      "%mailer_port%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Slugify Configuration
cocur_slugify:
    lowercase: true
    rulesets: [ "polish" ]

# Sentry error reporting
sentry:
    dsn: "%sentry_dsn%"

# Thumbnails
liip_imagine:
    loaders:
        default:
            filesystem:
                data_root: "%kernel.root_dir%/../public_html/"

    resolvers:
        default:
            web_path:
                web_root: "%kernel.root_dir%/../public_html/"

    filter_sets:
        cache: ~

        product_collection_thumb:
            quality: "%image.collection.quality%"
            filters:
                thumbnail: { size: ["%image.collection.width%", "%image.collection.height%"], mode: outbound }

        product_thumb:
            quality: "%image.product.small.quality%"
            filters:
                thumbnail: { size: ["%image.product.small.width%", "%image.product.small.height%"], mode: outbound }

        product_full:
            quality: "%image.product.big.quality%"
            filters:
                thumbnail: { size: ["%image.product.big.width%", "%image.product.big.height%"], mode: outbound }
