app:
    resource: "@AppBundle/Controller/"
    type:     annotation

order:
    resource: "@OrderBundle/Controller/"
    type:     annotation

product:
    resource: "@ProductBundle/Controller/"
    type:     annotation

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"
