# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    menu:
        class: AppBundle\Menu\Menu

    delivery_type_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - OrderBundle\Entity\DeliveryType

    product_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - ProductBundle\Entity\Product

    cart_repository:
        class: CartBundle\Repository\CartRepository
        arguments: ['@session', '@product_repository']

    temporary_order_repository:
        class: OrderBundle\Repository\SessionOrderRepository
        arguments: ['@session', '@delivery_type_repository']
