# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    menu:
        class: AppBundle\Menu\Menu
        arguments: ['@product_type_repository', '@product_collection_repository']

    realization_type_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - OrderBundle\Entity\RealizationType

    delivery_type_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - OrderBundle\Entity\DeliveryType

    product_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - ProductBundle\Entity\Product

    product_collection_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - ProductBundle\Entity\ProductCollection

    product_type_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - ProductBundle\Entity\ProductType

    product_image_listener:
        class: ProductBundle\Entity\Event\ProductImageListener
        arguments: ['%image.product.directory%']
        tags:
            - { name: doctrine.orm.entity_listener }
            - { name: doctrine.orm.entity_listener, entity_manager: custom }

    temporary_order_repository:
        class: OrderBundle\Repository\SessionOrderRepository
        arguments: ['@session', '@product_repository', '@realization_type_repository', '@delivery_type_repository']

    order_mailer:
        class: OrderBundle\Service\OrderMailer
        arguments: ['@mailer', '@templating', '%admin.mail%']
