parameters:
    admin_mail: '%env(ADMIN_MAIL)%'
    canonical_domain: '%env(CANONICAL_DOMAIN)%'
    samples_count: 2
    locale: 'pl'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Decarte\Shop\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Decarte\Shop\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    Decarte\Shop\Entity\Product\Event\ProductImageListener:
        arguments:
            - '%image.product.directory%'
        tags:
            - { name: doctrine.orm.entity_listener }

    Decarte\Shop\Form\Product\Event\ProductFormListener:
        arguments:
            - '%image.product.directory%'

    Decarte\Shop\Form\Product\ProductForm:
        arguments:
            $imageUrl: '%image.product.url%'

    Decarte\Shop\Service\GoogleExport:
        arguments:
            $canonicalDomain: '%env(CANONICAL_DOMAIN)%'
            $merchantId: '%env(GOOGLE_MERCHANT_ID)%'
            $googlePrivateKey: '%env(GOOGLE_PRIVATE_KEY)%'

    Decarte\Shop\Service\Payment\PayU:
        arguments:
            $environment: '%env(PAYU_ENVIRONMENT)%'
            $posId: '%env(PAYU_POS_ID)%'
            $signatureKey: '%env(PAYU_SIGNATURE_KEY)%'
            $clientId: '%env(PAYU_OAUTH_CLIENT_ID)%'
            $clientSecret: '%env(PAYU_OAUTH_CLIENT_SECRET)%'

    Decarte\Shop\Service\OrderMailer:
        arguments:
            $adminMail: '%env(ADMIN_MAIL)%'
            $attachmentDir: '%kernel.project_dir%/assets/doc'

    Decarte\Shop\Service\SamplesOrderMailer:
        arguments:
            $adminMail: '%env(ADMIN_MAIL)%'

    Decarte\Shop\Service\Url\ProductCollectionImageUrl:
        arguments:
            $canonicalDomain: '%env(CANONICAL_DOMAIN)%'
            $imagesDirectory: '%image.collection.url%'

    Decarte\Shop\Service\Url\ProductImageUrl:
        arguments:
            $canonicalDomain: '%env(CANONICAL_DOMAIN)%'
            $imagesDirectory: '%image.product.url%'

    Sentry\Integration\IgnoreErrorsIntegration:
        arguments:
            $options:
                ignore_exceptions:
                    - Symfony\Component\HttpKernel\Exception\NotFoundHttpException
